[workspace]
resolver = "3"
members = [
    "crates/linker",
    "crates/runtime",
    "crates/shell",
    "crates/update",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

# maintaining dependencies in root cargo.toml would be easier :P
[workspace.dependencies]
clap = { version = "4.6.7", features = ["cargo"] }
gtk4 = { version = "0.11.5", features = ["v4_22"] }
directories = "6.0.0"
zip = "8.6.0"
sha2 = "0.11.0"
runtime = { path = "crates/runtime" }
linker = { path = "crates/linker" }
update = { path = "crates/update" }

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"