[workspace]
resolver = "3"
members = [
    "crates/jni",
    "crates/linker",
    "crates/runtime",
    "crates/shell",
    "crates/update",
]
default-members = ["crates/shell"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.99.0"
license = "AGPL-3.0-or-later"
repository = "https://github.com/tachy0nnn/cork"

# maintaining dependencies in root cargo.toml would be easier :P
[workspace.dependencies]
clap = { version = "4.6.7", features = ["derive", "cargo"] }
gtk4 = { version = "0.11.5", features = ["v4_14"] }
directories = "6.0.0"
zip = "8.6.0"
sha2 = "0.11.0"
libc = "0.2.190"
jni = { path = "crates/jni" }
linker = { path = "crates/linker" }
runtime = { path = "crates/runtime" }
shell = { path = "crates/shell" }
update = { path = "crates/update" }

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
similar_names = "allow"
missing_safety_doc = "allow"
missing_panics_doc = "allow"
cast_possible_wrap = "allow"
too_many_lines = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
cast_possible_truncation = "allow"

[profile.release]
strip = true
