[package]
name = "shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cork"
path = "src/main.rs"

[dependencies]
clap.workspace = true
gtk4.workspace = true
runtime.workspace = true

[lints]
workspace = true